# Generated by Django 5.2.2 on 2025-06-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="courses_completed",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="courses_enrolled",
            field=models.ManyToManyField(blank=True, to="courses.course"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
