# Generated by Django 5.2.4 on 2025-07-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_duration_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='test_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
